### ISSUE TITLE
Performance drop from reverb 0.2.0 -> 0.3.1

### ISSUE THREAD

**Issue by piyushk** [deepmind/reverb#57] opened 2021-06-28 20:08 UTC
We've been looking to upgrade from reverb 0.2.0 to 0.3.1 to make use of the new TrajectoryWriter API, and noticed a performance drop using the old `ReverbWriter/ReverbDataset` means of using Reverb. Using a binary search of reverb commits, we've attributed the loss to https://github.com/deepmind/reverb/commit/af5f831956a5544993295d97b9ca7656d28faa98

A test script is attached [reverb_profiling.py.txt](https://github.com/deepmind/reverb/files/6729005/reverb_profiling.py.txt), and you can run it as follows:
```
python3 reverb_profiling.py trainer
python3 reverb_profiling.py --writers_per_worker 100 rollout_worker --trainer localhost:2121
```

With af5f831956a5544993295d97b9ca7656d28faa98 compiled against tensorflow 2.4.1:
```
Seconds per batch: 0.012515873205993558; Batches per second: 79.89854032087219 Samples per second: 163632.21057714624
Seconds per batch: 0.013269975135990535; Batches per second: 75.35809146226823 Samples per second: 154333.37131472534
Seconds per batch: 0.013190732322997065; Batches per second: 75.8108022749104 Samples per second: 155260.5230590165
```

With the preview commit 59f97a88050ac5f91b50cc9ddc97d3c29c631c1b compiled against tensorflow 2.4.1:
```
Seconds per batch: 0.0054205814140004804; Batches per second: 184.4820552675701 Samples per second: 377819.2491879836
Seconds per batch: 0.006230541972006904; Batches per second: 160.4996811662425 Samples per second: 328703.34702846466
Seconds per batch: 0.006633712397000636; Batches per second: 150.7451544706912 Samples per second: 308726.0763559756
```

The commit in question is large, and changes reverb to use `absl::Status` instead of `tensorflow::Status`. We're currently not sure why this was responsible.

**Comment by ebrevdo** [comment] 2021-06-28 21:34
TF has avoided moving to absl::Status for performance reasons, so it's totally possible that this change is indeed the culprit.  @acassirer should we try running some benchmarks against a rollback?

**Comment by ebrevdo** [comment] 2021-06-28 21:34
@piyushk do you get the performance drop *even without TrajectoryWriter/Dataset*?  or is that only w/ the new Trajectory code path that you see the issues?

**Comment by piyushk** [comment] 2021-06-28 21:39
@ebrevdo We get the performance drop even without the TrajectoryWriter/Dataset. You can run the old API script I provided against both commits to confirm. We do not believe it is related to the API change, but the new API also suffers from it.

**Comment by ebrevdo** [comment] 2021-07-07 15:52
@piyushk looks like this can happen when absl::Status is being created with an error code; in which case we start allocating on the heap.  do you have a cpu profile from server+client before and after the regression?

If it is indeed related to heap allocations, your mention of [switching to tcmalloc](http://goog-perftools.sourceforge.net/doc/tcmalloc.html) seems relevant.  Are these regressions with or without tcmalloc?

**Comment by piyushk** [comment] 2021-07-07 19:13
@ebrevdo 

- I'm seeing the performance drop both with and without `tcmalloc`. 
- However, It does seem that sampling runs faster when `tcmalloc` is used. 
 
Numbers are below. All testing was done inside a docker container. 

### With tcmalloc enabled via LD_PRELOAD

With the absl::Status commit af5f831 compiled against tensorflow 2.4.1:
```
Seconds per batch: 0.012224878983004601; Batches per second: 81.80040075572367 Samples per second: 167527.22074772208
Seconds per batch: 0.012608907806003117; Batches per second: 79.309010374705 Samples per second: 162424.85324739583
Seconds per batch: 0.012817850731997168; Batches per second: 78.01619951024259 Samples per second: 159777.17659697682
Seconds per batch: 0.012927682042005471; Batches per second: 77.35338761819284 Samples per second: 158419.73784205894
```

With the previous commit 59f97a8 compiled against tensorflow 2.4.1:
```
Seconds per batch: 0.005072607990994584; Batches per second: 197.13725203589613 Samples per second: 403737.09216951526
Seconds per batch: 0.006043225254004938; Batches per second: 165.4745533996577 Samples per second: 338891.885362499
Seconds per batch: 0.00618800658400869; Batches per second: 161.6029308346637 Samples per second: 330962.8023493913
Seconds per batch: 0.006495321592999971; Batches per second: 153.95696512974865 Samples per second: 315303.86458572524
```

### Without tcmalloc (aka regular malloc)

With the absl::Status commit af5f831 compiled against tensorflow 2.4.1:
```
Seconds per batch: 0.013892338610996376; Batches per second: 71.98212108136045 Samples per second: 147419.3839746262
Seconds per batch: 0.014323102891998132; Batches per second: 69.81727405998518 Samples per second: 142985.77727484965
Seconds per batch: 0.014902708711990271; Batches per second: 67.10189532158205 Samples per second: 137424.68161860004
Seconds per batch: 0.015094536081000115; Batches per second: 66.24913774320802 Samples per second: 135678.23409809003
```

With the previous commit 59f97a8 compiled against tensorflow 2.4.1:
```
Seconds per batch: 0.008303055481999763; Batches per second: 120.43759097694881 Samples per second: 246656.18632079117
Seconds per batch: 0.008634247113004676; Batches per second: 115.81785729688305 Samples per second: 237194.97174401648
Seconds per batch: 0.008963318904992775; Batches per second: 111.56581737184169 Samples per second: 228486.79397753178
Seconds per batch: 0.009183716329003801; Batches per second: 108.88838071378828 Samples per second: 223003.4037018384
```

**Comment by ebrevdo** [comment] 2021-07-09 17:00
I tried building those hashes against tf-2.4.1 but ran into issues with missing include files from the TF build.  I'll try building against tf-nightly and see if I can reproduce.

**Comment by ebrevdo** [comment] 2021-07-09 17:09
Scratch that; I'm now able to build against tf 2.4.1 and will run your profiling w/ perf counters now.

**Comment by ebrevdo** [comment] 2021-07-09 17:28
I compiled with clang-11.0.1 via:

```
CC=clang CXX=clang bazel build -c opt --copt=-g2 reverb/pip_package:build_pip_package
```

and i don't see a big performance delta (though I do see some): from 64 batch/sec to 60 batch/sec approximately.

This is on a 6 core machine w/ `Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz.`

I'll look at the perf counters but I don't expect a huge difference given the performance seems the same.

Perf counters ran via:

```
perf record -o reverb_profiling_trainer.data python reverb_profiling.py trainer &
perf record -o reverb_profiling_workers.data python reverb_profiling.py --writers_per_worker 100 rollout_worker --trainer localhost:2121 &
```

**Comment by ebrevdo** [comment] 2021-07-09 17:36
I do see that after the move, we spend a reasonable amount of time in the new StatusBuilder object:

![image](https://user-images.githubusercontent.com/1794715/125116269-56781980-e0a1-11eb-8342-6925e263344d.png)


Previously, Status-related code was about half as much of the execution time on the trainer:

![image](https://user-images.githubusercontent.com/1794715/125116372-7dcee680-e0a1-11eb-8d29-2bdcab2205fe.png)

**Comment by ebrevdo** [comment] 2021-07-09 17:48
Welp; as it turns out we forked StatusBuilder a bit too early!  A month after our fork, Jeff Dean hand-optimized the StatusBuilder representation so that it would be less likely to fall outside cache in the typical codepath (OK Status).  I'll see if I can merge his changes into our fork.

The TF version of the macros we use for `REVERB_RETURN_IF_ERROR` is much simpler; maybe I'll just use those instead :)

**Comment by piyushk** [comment] 2021-07-09 17:59
@ebrevdo Thanks a lot! Please do let me know if you have a branch for me to test on. 

Your machine is more powerful than mine, so I'm still trying to figure out why you're seeing lower throughput than me. Here are some thoughts:
- I'm using an Ubuntu 18.04 container on my local machine to run these tests.
- I used `bazel build -c opt //reverb/pip_package:build_pip_package` to build my images. I've already verified that `--copt=-g2` has no impact. I assume it's compiling via gcc since I don't have clang installed. I'll try and test that later this afternoon.
- Using perf definitely reduces the throughput numbers a bit. That being said, with perf and tcmalloc, I'm still seeing ~100 batches/second.

> and i don't see a big performance delta (though I do see some): from 64 batch/sec to 60 batch/sec approximately.

- Was 64/60 with perf and regular malloc?
- Are you running on your host machine directly or in a docker container?

I'll try my best to get you to a point where you can reproduce our performance drop.

**Comment by ebrevdo** [comment] 2021-07-09 18:04
With much simpler status macros and getting rid of status builder, i'm seeing 75+ batches/sec.  I'll create my own branch on github for you to try.

**Comment by ebrevdo** [comment] 2021-07-09 19:05
Try building from my [after](https://github.com/ebrevdo/reverb/tree/after) branch.  This should build against TF 2.4.1.  LMK if it helps.

**Comment by ebrevdo** [comment] 2021-07-09 19:37
Yes; I'm writing up an internal PR to get this checked into master sometime today / tomorrow.

**Closed** 2021-07-12 16:06 UTC
