### ISSUE TITLE
Controlling the number of spawned threads

### ISSUE THREAD

**Issue by PPSantos** [deepmind/reverb#5] opened 2020-06-25 14:04 UTC
Hi all, thanks for open-sourcing this software!

I'm wondering if it's possible to somehow limit the number of threads spawned by the reverb service. 

As an example, gRPC allows customizing the number of threads used to process incoming request (server_builder.cc):

https://github.com/grpc/grpc/blob/6a477958c06ef6a09e7628fd5b1bf4c174ca78b8/src/cpp/server/server_cc.cc#L59-L64
https://github.com/grpc/grpc/blob/88af358f9ec9b2a84f82b3f4e795df62c920c29b/src/cpp/server/server_builder.cc#L152-L169

However, it looks that this kind of configuration is not exposed to the user in Reverb, i.e. the user is unable to tweak these parameters:

https://github.com/deepmind/reverb/blob/da75a95c4a0aa96af797a6bed22cac3c73bc0448/reverb/cc/platform/default/server.cc#L34-L57

Am I missing something? Is it possible to somehow tweak these thread-related parameters, especially the threadpool size of the gRPC server?

Thanks!

**Comment by sabelaraga** [comment] 2020-07-15 12:21
Hey Pedro, the problem is that by limiting the number of threads you may end up with a deadlock if you try to open many connections (e.g., let's say all the inserters connect to reverb using the available threads, and the sampler cannot connect any more).

**Comment by sabelaraga** [comment] 2020-07-21 07:08
Closing this, but please reopen if you have more comments.

**Closed by sabelaraga** 2020-07-21 07:08 UTC
