### ISSUE TITLE
ReplayDataset not working on TPU

### ISSUE THREAD

**Issue by MorganeAyle** [deepmind/reverb#68] opened 2021-09-10 15:22 UTC
Hello, 

I am getting the following error when trying to sample from the ReplayDataset after having initialized a TPU:
`tensorflow.python.framework.errors_impl.NotFoundError: 'ReverbDataset' is neither a type of a primitive operation nor a name of a function registered in binary running on n-9f826cf4-w-0. Make sure the operation or function is registered in the binary running in this process. [Op:DeleteIterator]`

I am using tensorflow 2.4.1 and reverb 0.2.0 versions. Everything works fine when sampling and training on a GPU with the same code. Any idea what this issue is and how to solve it?

**Comment by fastturtle** [comment] 2021-09-14 09:29
Duplicate of #29.

**Closed by fastturtle** 2021-09-14 09:29 UTC
